"""Change coordinate types to Float

Revision ID: 21b98dba438b
Revises: e5fdf24a31b1
Create Date: 2025-05-08 13:08:13.005412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21b98dba438b'
down_revision = 'e5fdf24a31b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=sa.NUMERIC(precision=30, scale=25),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('longitude',
               existing_type=sa.NUMERIC(precision=30, scale=25),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.drop_column('new_field')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new_field', sa.VARCHAR(length=100), nullable=True))
        batch_op.alter_column('longitude',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=30, scale=25),
               existing_nullable=True)
        batch_op.alter_column('latitude',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=30, scale=25),
               existing_nullable=True)

    # ### end Alembic commands ###
