"""remove new field property

Revision ID: e5fdf24a31b1
Revises: 
Create Date: 2025-05-08 12:43:51.707476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5fdf24a31b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('property')
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new_field', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_column('new_field')

    op.create_table('property',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('address', sa.VARCHAR(length=200), nullable=False),
    sa.Column('latitude', sa.FLOAT(), nullable=True),
    sa.Column('longitude', sa.FLOAT(), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=True),
    sa.Column('bedrooms', sa.INTEGER(), nullable=True),
    sa.Column('bathrooms', sa.FLOAT(), nullable=True),
    sa.Column('square_feet', sa.INTEGER(), nullable=True),
    sa.Column('lot_size', sa.FLOAT(), nullable=True),
    sa.Column('year_built', sa.INTEGER(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
